[package]
name = "quarry-egui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
eframe.workspace = true
egui_extras.workspace = true
quarry-core = { path = "../../crates/quarry-core" }
rfd = { version = "0.17.2", default-features = false }
tempfile = "3.27.0"
